batch_type: folded
batch_size: 32
accum_grad: 8
max_epoch: 100
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

# replace frontend with wav2vec frontend
frontend: wav2vec
frontend_conf:
    model_path: /home/ras306/Classwork/Project/Wav2Vec/model/wav2vec_small.pt 
    #model_path: /home/ras306/Classwork/Project/Wav2Vec/model/checkpoint_best.pt
    embedding_dim: 512

#input_size: 257687
encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: linear
    normalize_before: true


decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false
    is_wav2vec_encoder: false # if use wav2vec encoder set to true

optim: adam
optim_conf:
    lr: 0.005
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 30000
